# Generated by Django 2.0.13 on 2019-05-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='color',
            field=models.CharField(choices=[('blue', 'blue'), ('orange', 'orange'), ('pink', 'pink'), ('gray', 'gray')], max_length=20, null=True),
        ),
    ]
